export enum Sigil {
    Sprinter = 'sprinter',
    DeathTouch = 'death-touch',
    Fledgling = 'fledgling',
    Hoarder = 'hoarder',
    Burrower = 'burrower',
    CopyOnPlay = 'copy-on-play',
    LooseTail = 'loose-tail',
    Waterborne = 'waterborne',
    KrakenWaterborne = 'kraken-waterborne',
    Airborne = 'airborne',
    AntiAir = 'anti-air',
    Unkillable = 'unkillable',
    SharpQuills = 'sharp-quills',
    Hefty = 'hefty',
    Guardian = 'guardian',
    Repulsive = 'repulsive',
    TwoHit = 'two-hit',
    ThreeHit = 'three-hit',
    Frozen = 'frozen',
    Leader = 'leader',
    Stinky = 'stinky',
    Trap = 'trap',
    Handy = 'handy',
    Detonator = 'detonator',
    Sentry = 'sentry',
    Looter = 'looter',

    SquirrelShedder = 'squirrel-shedder',
    Dam = 'dam',
    Rabbit = 'rabbit',
    Bee = 'bee',
    AntSpawner = 'ant-spawner',
    ManyLives = 'many-lives',
    ThreeBlood = 'three-blood',

    BoneKing = 'bone-king',
    CorpseEater = 'corpse-eater',
    BoneDigger = 'bone-digger',
    Brittle = 'brittle',
    SkeletonCrew = 'skeleton-crew',
    DoubleDeath = 'double-death',

    GreenMox = 'green-mox',
    BlueMox = 'blue-mox',
    OrangeMox = 'orange-mox',
    GemAnimator = 'gem-animator',
    RubyHeart = 'ruby-heart',
    MentalGymnastics = 'mental-gymnastics',
    GemDependant = 'gem-dependant',
    GreatMox = 'great-mox',

    AttackConduit = 'attack-conduit',
    SpawnConduit = 'spawn-conduit',
    NullConduit = 'null-conduit',
    BatteryBearer = 'battery-bearer',
    EnergyConduit = 'energy-conduit',
    BombSpewer = 'bomb-spewer',

    PowerDice = 'power-dice',
    Enlarge = 'enlarge',
    Disentomb = 'disentomb',
    EnergyGun = 'energy-gun',
    TrueScholar = 'true-scholar',
    Stimulate = 'stimulate',
    Bonehorn = 'bonehorn',
}
