import { CardPrint, MoxType } from '../engine/Card';

export const prints: Record<string, CardPrint> = {
    starvation: {
        name: 'Starvation',
        portrait: 'starvation',
        power: 1,
        health: 1,
        sigils: [ 'voidDamage' ],
    },
    greaterSmoke: {
        name: 'Greater Smoke',
        portrait: 'greaterSmoke',
        face: 'rare',
        power: 1,
        health: 3,
        sigils: [ 'fourBones' ],
    },
    adder: {
        name: 'Adder',
        portrait: 'adder',
        power: 2,
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'deathTouch' ],
    },
    bat: {
        name: 'Bat',
        portrait: 'bat',
        power: 2,
        health: 1,
        cost: { type: 'bone', amount: 4 },
        sigils: [ 'airborne' ],
    },
    beaver: {
        name: 'Beaver',
        portrait: 'beaver',
        power: 1,
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'damBuilder' ],
    },
    dam: {
        name: 'Dam',
        portrait: 'dam',
        power: 0,
        health: 2,
        noSac: true,
        sigils: [ 'mightyLeap' ],
    },
    bee: {
        name: 'Bee',
        portrait: 'bee',
        power: 1,
        health: 1,
        sigils: [ 'airborne' ],
    },
    beehive: {
        name: 'Beehive',
        portrait: 'beehive',
        power: 0,
        health: 2,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'beesWithin' ],
    },
    blackGoat: {
        name: 'Black Goat',
        portrait: 'blackGoat',
        power: 0,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'threeSacs' ],
    },
    bloodhound: {
        name: 'Bloodhound',
        portrait: 'bloodhound',
        power: 2,
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'chaseOpposingPlay' ],
    },
    bullfrog: {
        name: 'Bullfrog',
        portrait: 'bullfrog',
        power: 1,
        health: 3,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'mightyLeap' ],
    },
    cat: {
        name: 'Cat',
        desc: 'Note: This card was changed to rare due to the amount of advantage given by this card.',
        portrait: 'cat',
        face: 'rare',
        frame: 'nature_frame',
        power: 0,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'manyLives' ],
    },
    catUndead: {
        name: 'Undead Cat',
        portrait: 'catUndead',
        power: 3,
        health: 6,
        cost: { type: 'blood', amount: 1 },
    },
    cockroach: {
        name: 'Cockroach',
        portrait: 'cockroach',
        power: 1,
        health: 1,
        cost: { type: 'bone', amount: 4 },
        sigils: [ 'unkillable' ],
    },
    corpseMaggots: {
        name: 'Corpse Maggots',
        portrait: 'corpseMaggots',
        power: 1,
        health: 2,
        cost: { type: 'bone', amount: 4 },
        sigils: [ 'corpseEater' ],
    },
    theDaus: {
        name: 'The Daus',
        portrait: 'theDaus',
        face: 'rare',
        frame: 'nature_frame',
        power: 2,
        health: 2,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'bellist' ],
    },
    chime: {
        name: 'Chime',
        portrait: 'chime',
        power: 0,
        health: 1,
        noSac: true,
        sigils: [ 'mightyLeap' ],
    },
    direWolfPup: {
        name: 'Dire Wolf Pup',
        portrait: 'direWolfPup',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'boneDigger', 'evolve' ],
        evolution: 'direWolf',
    },
    direWolf: {
        name: 'Dire Wolf',
        portrait: 'direWolf',
        power: 2,
        health: 5,
        cost: { type: 'blood', amount: 3 },
        sigils: [ 'doubleAttack' ],
    },
    elk: {
        name: 'Elk',
        portrait: 'elk',
        power: 2,
        health: 4,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'strafe' ],
    },
    elkCub: {
        name: 'Elk Fawn',
        portrait: 'elkCub',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'strafe', 'evolve' ],
        evolution: 'elk',
    },
    fieldMice: {
        name: 'Field Mice',
        portrait: 'fieldMice',
        power: 2,
        health: 2,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'drawCopy' ],
    },
    fieldMiceFused: {
        name: 'Spore Mice',
        portrait: 'fieldMiceFused',
        fused: true,
        power: 2,
        health: 2,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'drawCopy', 'drawCopy' ],
    },
    hawk: {
        name: 'Hawk',
        portrait: 'hawk',
        power: 3,
        health: 1,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'airborne' ],
    },
    hrokkall: {
        name: 'Hrokkall',
        portrait: 'hrokkall',
        face: 'rare',
        frame: 'nature_frame',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'waterborne', 'gainBattery' ],
    },
    ratKing: {
        name: 'Rat King',
        portrait: 'ratKing',
        power: 2,
        health: 1,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'fourBones' ],
    },
    ravenEgg: {
        name: 'Raven Egg',
        portrait: 'ravenEgg',
        power: 0,
        health: 2,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'evolve' ],
        evolution: 'raven',
    },
    kingfisher: {
        name: 'Kingfisher',
        portrait: 'kingfisher',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'airborne', 'waterborne' ],
    },
    kraken: {
        name: 'Great Kraken',
        desc: 'Note: This card\'s effect was changed due to it sucking.',
        portrait: 'kraken',
        face: 'rare',
        frame: 'nature_frame',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'waterborneTentacle' ],
    },
    // longElk: {
    //     name: 'Long Elk',
    //     portrait: 'longElk',
    //     face: 'rare',
    //     frame: 'nature_frame',
    //     power: 1,
    //     health: 2,
    //     cost: { type: 'bone', amount: 4 },
    //     sigils: [ 'strafe', 'deathTouch' ],
    // },
    // vertebrae: {
    //     name: 'Vertebrae',
    //     portrait: 'vertebrae',
    //     power: 0,
    //     health: 1,
    // },
    alpha: {
        name: 'Alpha',
        portrait: 'alpha',
        power: 1,
        health: 2,
        cost: { type: 'bone', amount: 4 },
        sigils: [ 'leader' ],
    },
    magpie: {
        name: 'Magpie',
        desc: 'This card was unused in act 2, but had art.',
        portrait: 'magpie',
        face: 'rare',
        frame: 'nature_frame',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'airborne', 'hoarder' ],
    },
    mantis: {
        name: 'Mantis',
        portrait: 'mantis',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'bistrike' ],
    },
    mantisGod: {
        name: 'Mantis God',
        portrait: 'mantisGod',
        face: 'rare',
        frame: 'nature_frame',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'tristrike' ],
    },
    mole: {
        name: 'Mole',
        portrait: 'mole',
        power: 0,
        health: 4,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'chaseAttack' ],
    },
    moleMan: {
        name: 'Mole Man',
        portrait: 'moleMan',
        face: 'rare',
        frame: 'nature_frame',
        power: 0,
        health: 6,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'chaseAttack', 'mightyLeap' ],
    },
    mooseBuck: {
        name: 'Moose Buck',
        portrait: 'mooseBuck',
        power: 3,
        health: 7,
        cost: { type: 'blood', amount: 3 },
        sigils: [ 'strafePush' ],
    },
    opossum: {
        name: 'Opossum',
        portrait: 'opossum',
        power: 1,
        health: 1,
        cost: { type: 'bone', amount: 2 },
    },
    ouroboros: {
        name: 'Ouroboros',
        desc: 'This card gains 1 power and 1 health each time it perishes.',
        portrait: 'ouroboros',
        face: 'rare',
        frame: 'nature_frame',
        power: 1,
        health: 1,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'unkillable' ],
    },
    rabbit: {
        name: 'Rabbit',
        portrait: 'rabbit',
        power: 0,
        health: 1,
    },
    skunk: {
        name: 'Skunk',
        portrait: 'skunk',
        power: 0,
        health: 3,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'stinky' ],
    },
    coyote: {
        name: 'Coyote',
        portrait: 'coyote',
        power: 2,
        health: 1,
        cost: { type: 'bone', amount: 4 },
    },
    greatWhite: {
        name: 'Great White',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'greatWhite',
        power: 4,
        health: 2,
        cost: { type: 'blood', amount: 3 },
        sigils: [ 'waterborne' ],
    },
    grizzly: {
        name: 'Grizzly',
        portrait: 'grizzly',
        power: 4,
        health: 5,
        cost: { type: 'blood', amount: 3 },
    },
    porcupine: {
        name: 'Porcupine',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'porcupine',
        power: 1,
        health: 2,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'sharp' ],
    },
    pronghorn: {
        name: 'Pronghorn',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'pronghorn',
        power: 1,
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'bistrike', 'strafe' ],
    },
    rattler: {
        name: 'Rattler',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'rattler',
        power: 3,
        health: 1,
        cost: { type: 'bone', amount: 6 },
    },
    raven: {
        name: 'Raven',
        portrait: 'raven',
        power: 2,
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'airborne' ],
    },
    salmon: {
        name: 'Salmon',
        portrait: 'salmon',
        power: 2,
        health: 2,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'waterborne', 'strafe' ],
    },
    riverSnapper: {
        name: 'River Snapper',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'riverSnapper',
        power: 1,
        health: 6,
        cost: { type: 'blood', amount: 2 },
    },
    sparrow: {
        name: 'Sparrow',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'sparrow',
        power: 1,
        health: 2,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'airborne' ],
    },
    strangeLarva: {
        name: 'Strange Larva',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'strangeLarva',
        face: 'rare',
        frame: 'nature_frame',
        power: 0,
        health: 3,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'evolve' ],
        evolution: 'strangePupa',
    },
    strangePupa: {
        name: 'Strange Pupa',
        portrait: 'strangePupa',
        face: 'rare',
        frame: 'nature_frame',
        power: 0,
        health: 3,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'evolve' ],
        evolution: 'mothman',
    },
    mothman: {
        name: 'Mothman',
        portrait: 'mothman',
        face: 'rare',
        frame: 'nature_frame',
        power: 7,
        health: 3,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'airborne' ],
    },
    turkeyVulture: {
        name: 'Turkey Vulture',
        desc: 'Ported from Act 1. Act 2 sprite by syntaxevasion.',
        portrait: 'turkeyVulture',
        power: 3,
        health: 3,
        cost: { type: 'bone', amount: 8 },
        sigils: [ 'airborne' ],
    },
    bellTentacle: {
        name: 'Bell Tentacle',
        portrait: 'bellTentacle',
        power: 'bells',
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'waterborneTentacle' ],
    },
    handTentacle: {
        name: 'Hand Tentacle',
        portrait: 'handTentacle',
        power: 'hand',
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'waterborneTentacle' ],
    },
    mirrorTentacle: {
        name: 'Mirror Tentacle',
        portrait: 'mirrorTentacle',
        power: 'mirror',
        health: 3,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'waterborneTentacle' ],
    },
    squirrel: {
        name: 'Squirrel',
        portrait: 'squirrel',
        power: 0,
        health: 1,
    },
    squirrelBall: {
        name: 'Squirrel Ball',
        portrait: 'squirrelBall',
        power: 0,
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'squirrelStrafe' ],
    },
    stoat: {
        name: 'Stoat',
        desc: 'Note: Health was increased to 3 to make it better than Bullfrog in at least one way. Bears a unique ability from Act 1.',
        portrait: 'stoat',
        power: 1,
        health: 3,
        cost: { type: 'blood', amount: 1 },
    },
    urayuli: {
        name: 'Urayuli',
        portrait: 'urayuli',
        face: 'rare',
        frame: 'nature_frame',
        power: 7,
        health: 7,
        cost: { type: 'blood', amount: 4 },
    },
    warren: {
        name: 'Warren',
        portrait: 'warren',
        power: 0,
        health: 2,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'drawRabbit' ],
    },
    wolf: {
        name: 'Wolf',
        portrait: 'wolf',
        power: 3,
        health: 2,
        cost: { type: 'blood', amount: 2 },
    },
    wolfCub: {
        name: 'Wolf Cub',
        portrait: 'wolfCub',
        power: 1,
        health: 2,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'evolve' ],
        evolution: 'wolf',
    },
    workerAnt: {
        name: 'Worker Ant',
        portrait: 'workerAnt',
        power: 'ants',
        health: 2,
        cost: { type: 'blood', amount: 1 },
    },
    queenAnt: {
        name: 'Ant Queen',
        portrait: 'queenAnt',
        power: 'ants',
        health: 3,
        cost: { type: 'blood', amount: 2 },
        sigils: [ 'antSpawner' ],
    },
    flyingAnt: {
        name: 'Flying Ant',
        portrait: 'flyingAnt',
        power: 'ants',
        health: 1,
        cost: { type: 'blood', amount: 1 },
        sigils: [ 'airborne' ],
    },
    curveHopper: {
        name: 'Curve Hopper',
        portrait: 'curveHopper',
        face: 'rare',
        frame: 'tech_frame',
        power: 2,
        health: 3,
        cost: { type: 'energy', amount: 4 },
    },
    automaton: {
        name: 'Automaton',
        desc: 'Note: The energy cost of this card was reduced to make it less terrible.',
        portrait: 'automaton',
        power: 1,
        health: 1,
        cost: { type: 'energy', amount: 2 },
    },
    energyBot: {
        name: 'Energy Bot',
        portrait: 'energyBot',
        power: 0,
        health: 1,
        cost: { type: 'energy', amount: 2 },
        sigils: [ 'gainBattery' ],
    },
    bolthound: {
        name: 'Bolthound',
        desc: 'Note: Health was increased to 3 to make it equivalent to other "Hound" cards.',
        portrait: 'bolthound',
        power: 2,
        health: 3,
        cost: { type: 'energy', amount: 6 },
        sigils: [ 'chaseOpposingPlay' ],
    },
    doubleGunner: {
        name: 'Double Gunner',
        portrait: 'doubleGunner',
        power: 2,
        health: 1,
        cost: { type: 'energy', amount: 6 },
        sigils: [ 'bistrike' ],
    },
    explodeBot: {
        name: 'Explode Bot',
        portrait: 'explodeBot',
        power: 1,
        health: 1,
        cost: { type: 'energy', amount: 2 },
        noSac: true,
        sigils: [ 'detonator' ],
    },
    gamblobot: {
        name: 'Gamblobot',
        desc: 'Note: The cost of this ability was increased to 2 energy due to this card being very strong for its cost.',
        portrait: 'gamblobot',
        power: 0,
        health: 1,
        cost: { type: 'energy', amount: 3 },
        // sigils: [ 'activatedDiceRollEnergy' ],
    },
    insectodrone: {
        name: 'Insectodrone',
        portrait: 'insectodrone',
        power: 1,
        health: 2,
        cost: { type: 'energy', amount: 3 },
        sigils: [ 'airborne' ],
    },
    plasmaJimmy: {
        name: 'Plasma Jimmy',
        portrait: 'plasmaJimmy',
        face: 'rare',
        frame: 'tech_frame',
        power: 0,
        health: 3,
        cost: { type: 'energy', amount: 2 },
        // sigils: [ 'activatedDealDamage' ],
    },
    steelMice: {
        name: 'Steel Mice',
        portrait: 'steelMice',
        power: 1,
        health: 1,
        cost: { type: 'energy', amount: 4 },
        sigils: [ 'drawCopy' ],
    },
    sentryBot: {
        name: 'Sentry Drone',
        desc: 'Note: The sentry sigil now triggers when this card is pushed by another card.',
        portrait: 'sentryBot',
        power: 0,
        health: 1,
        cost: { type: 'energy', amount: 1 },
        sigils: [ 'sentry' ],
    },
    sentryBotFused: {
        name: 'Sentry Spore',
        portrait: 'sentryBotFused',
        fused: true,
        power: 0,
        health: 1,
        cost: { type: 'energy', amount: 1 },
        sigils: [ 'sentry', 'sentry' ],
    },
    shutterbug: {
        name: 'Shutterbug',
        desc: 'Note: The sentry sigil now triggers when this card is pushed by another card.',
        portrait: 'shutterbug',
        face: 'rare',
        frame: 'tech_frame',
        power: 1,
        health: 1,
        cost: { type: 'energy', amount: 5 },
        sigils: [ 'deathTouch', 'sentry' ],
    },
    sniperBot: {
        name: 'Sniper Bot',
        portrait: 'sniperBot',
        power: 1,
        health: 1,
        cost: { type: 'energy', amount: 3 },
    },
    steambot: {
        name: 'Steambot',
        desc: 'Note: This card\'s attack was increased to make it worth 6 energy.',
        portrait: 'steambot',
        power: 3,
        health: 2,
        cost: { type: 'energy', amount: 6 },
    },
    gemModule: {
        name: 'Mox Module',
        portrait: 'gemModule',
        face: 'rare',
        frame: 'tech_frame',
        power: 0,
        health: 3,
        cost: { type: 'energy', amount: 3 },
        sigils: [ 'gainGemAll' ],
        tribes: ['mox'],
    },
    thickBot: {
        name: 'Thick Droid',
        portrait: 'thickBot',
        power: 1,
        health: 3,
        cost: { type: 'energy', amount: 5 },
    },
    draugr: {
        name: 'Draugr',
        portrait: 'draugr',
        face: 'terrain',
        power: 0,
        health: 1,
        cost: { type: 'bone', amount: 1 },
        noSac: true,
        sigils: [ 'frozen' ],
        evolution: 'skeleton',
    },
    banshee: {
        name: 'Banshee',
        portrait: 'banshee',
        power: 1,
        health: 3,
        cost: { type: 'bone', amount: 3 },
        sigils: [ 'airborne' ],
    },
    bonehound: {
        name: 'Bonehound',
        portrait: 'bonehound',
        power: 2,
        health: 3,
        cost: { type: 'bone', amount: 7 },
        sigils: [ 'chaseOpposingPlay' ],
    },
    boneHeap: {
        name: 'Bone Heap',
        portrait: 'boneHeap',
        face: 'rare',
        frame: 'undead_frame',
        power: 0,
        health: 1,
        // sigils: [ 'activatedStatsUp' ],
    },
    drownedSoul: {
        name: 'Drowned Soul',
        portrait: 'drownedSoul',
        face: 'rare',
        frame: 'undead_frame',
        power: 1,
        health: 1,
        cost: { type: 'bone', amount: 4 },
        sigils: [ 'waterborne', 'deathTouch' ],
    },
    walkers: {
        name: 'The Walkers',
        portrait: 'walkers',
        power: 2,
        health: 2,
        cost: { type: 'bone', amount: 5 },
        sigils: [ 'fourBones' ],
    },
    franknstein: {
        name: 'Frank & Stein',
        portrait: 'franknstein',
        power: 2,
        health: 2,
        cost: { type: 'bone', amount: 5 },
    },
    pharoahsPets: {
        name: 'Pharoah\'s Pets',
        portrait: 'pharoahsPets',
        power: 0,
        health: 1,
        cost: { type: 'bone', amount: 6 },
        sigils: [ 'threeSacs', 'manyLives' ],
    },
    ghostShip: {
        name: 'Ghost Ship',
        portrait: 'ghostShip',
        power: 0,
        health: 1,
        cost: { type: 'bone', amount: 2 },
        sigils: [ 'waterborne', 'skeletonStrafe' ],
    },
    gravedigger: {
        name: 'Gravedigger',
        portrait: 'gravedigger',
        power: 0,
        health: 3,
        cost: { type: 'bone', amount: 1 },
        sigils: [ 'boneDigger' ],
    },
    gravediggerFused: {
        name: 'Sporedigger',
        portrait: 'gravediggerFused',
        fused: true,
        power: 0,
        health: 3,
        cost: { type: 'bone', amount: 1 },
        sigils: [ 'boneDigger', 'boneDigger' ],
    },
    headlessHorseman: {
        name: 'Headless Horseman',
        portrait: 'headlessHorseman',
        face: 'rare',
        frame: 'undead_frame',
        power: 5,
        health: 5,
        cost: { type: 'bone', amount: 13 },
        sigils: [ 'airborne', 'strafe' ],
    },
    mummy: {
        name: 'Mummy Lord',
        portrait: 'mummy',
        power: 3,
        health: 3,
        cost: { type: 'bone', amount: 8 },
    },
    necromancer: {
        name: 'Necromancer',
        portrait: 'necromancer',
        face: 'rare',
        frame: 'undead_frame',
        power: 1,
        health: 2,
        cost: { type: 'bone', amount: 3 },
        sigils: [ 'doubleDeath' ],
    },
    revenant: {
        name: 'Revenant',
        portrait: 'revenant',
        power: 3,
        health: 1,
        cost: { type: 'bone', amount: 3 },
        sigils: [ 'brittle' ],
    },
    sarcophagus: {
        name: 'Sarcophagus',
        portrait: 'sarcophagus',
        power: 0,
        health: 2,
        cost: { type: 'bone', amount: 4 },
        sigils: [ 'evolve' ],
        evolution: 'mummy',
    },
    skeleton: {
        name: 'Skeleton',
        portrait: 'skeleton',
        power: 1,
        health: 1,
        sigils: [ 'brittle' ],
    },
    skeletonMage: {
        name: 'Skelemagus',
        desc: 'Note: Was given energy cost due to being too spammable and easy to draw into with Blue Mage.',
        portrait: 'skeletonMage',
        power: 4,
        health: 1,
        cost: { type: 'energy', amount: 4 },
        sigils: [ 'brittle', 'gemDependant' ],
    },
    tombRobber: {
        name: 'Tomb Robber',
        desc: 'Note: Withered corpses have the Boneless sigil and will not drop bones.This change was made to prevent multiple infinite combos involving Tomb Robber.',
        portrait: 'tombRobber',
        face: 'rare',
        frame: 'undead_frame',
        power: 0,
        health: 2,
        // sigils: [ 'activatedDrawSkeleton' ],
    },
    zombie: {
        name: 'Zombie',
        desc: 'This card was given the stinky sigil to differentiate it from Opossom. Suggested by FishGuy101.',
        portrait: 'zombie',
        power: 1,
        health: 1,
        cost: { type: 'bone', amount: 3 },
        sigils: [ 'stinky' ],
    },
    gourmage: {
        name: 'Gourmage',
        portrait: 'gourmage',
        power: 0,
        health: 2,
        cost: { type: 'mox', needs: MoxType.Green },
        // sigils: [ 'activatedStatsUp' ],
    },
    blueMage: {
        name: 'Blue Mage',
        portrait: 'blueMage',
        face: 'rare',
        frame: 'wizard_frame',
        power: 0,
        health: 1,
        cost: { type: 'mox', needs: MoxType.Blue },
        sigils: [ 'gemsDraw' ],
    },
    blueMageFused: {
        name: 'Blue Sporemage',
        portrait: 'blueMageFused',
        fused: true,
        power: 0,
        health: 1,
        cost: { type: 'mox', needs: MoxType.Blue },
        sigils: [ 'gemsDraw', 'gemsDraw' ],
    },
    hoverMage: {
        name: 'Hover Mage',
        portrait: 'hoverMage',
        power: 1,
        health: 2,
        cost: { type: 'mox', needs: MoxType.Blue },
        sigils: [ 'airborne' ],
    },
    forceMage: {
        name: 'Force Mage',
        desc: 'Dies to removal.',
        portrait: 'forceMage',
        power: 0,
        health: 1,
        cost: { type: 'mox', needs: MoxType.Blue },
        sigils: [ 'voidDamage' ],
    },
    gemFiend: {
        name: 'Gem Fiend',
        portrait: 'gemFiend',
        power: 2,
        health: 1,
        cost: { type: 'mox', needs: MoxType.Blue },
        sigils: [ 'gemDependant' ],
    },
    greenMage: {
        name: 'Green Mage',
        desc: 'This card\'s attack is equal to the number of "Mox" cards you possess.',
        portrait: 'greenMage',
        power: 'moxes',
        health: 2,
        cost: { type: 'mox', needs: MoxType.Green },
    },
    juniorSage: {
        name: 'Junior Sage',
        portrait: 'juniorSage',
        power: 1,
        health: 3,
        cost: { type: 'mox', needs: MoxType.Green },
    },
    mageKnight: {
        name: 'Mage Knight',
        portrait: 'mageKnight',
        power: 1,
        health: 3,
        cost: { type: 'mox', needs: MoxType.Orange },
        sigils: [ 'gemDependant' ],
    },
    masterBG: {
        name: 'Master Bleene',
        portrait: 'masterBG',
        face: 'rare',
        frame: 'wizard_frame',
        power: 0,
        health: 4,
        cost: { type: 'mox', needs: MoxType.Green | MoxType.Blue },
        // sigils: [ 'activatedSacrificeDraw' ],
    },
    masterGO: {
        name: 'Master Goranj',
        desc: 'He got buffed a while back. Thanks FishGuy101!',
        portrait: 'masterGO',
        face: 'rare',
        frame: 'wizard_frame',
        power: 2,
        health: 4,
        cost: { type: 'mox', needs: MoxType.Green | MoxType.Orange },
        sigils: [ 'gemDependant', 'bistrike' ],
    },
    masterOB: {
        name: 'Master Orlu',
        desc: 'Note: Attack was increased to make it an acceptable rare card and to demonstrate its sigil effect more clearly.',
        portrait: 'masterOB',
        face: 'rare',
        frame: 'wizard_frame',
        power: 1,
        health: 3,
        cost: { type: 'mox', needs: MoxType.Orange | MoxType.Blue },
        sigils: [ 'airborne', 'looter' ],
    },
    moxG: {
        name: 'Emerald Mox',
        portrait: 'moxG',
        power: 0,
        health: 1,
        noSac: true,
        sigils: [ 'gainGemGreen' ],
        tribes: ['mox'],
    },
    moxO: {
        name: 'Ruby Mox',
        portrait: 'moxO',
        power: 0,
        health: 1,
        noSac: true,
        sigils: [ 'gainGemOrange' ],
        tribes: ['mox'],
    },
    moxB: {
        name: 'Sapphire Mox',
        portrait: 'moxB',
        power: 0,
        health: 1,
        noSac: true,
        sigils: [ 'gainGemBlue' ],
        tribes: ['mox'],
    },
    moxAll: {
        name: 'Magnus Mox',
        portrait: 'moxAll',
        face: 'rare',
        frame: 'wizard_frame',
        power: 0,
        health: 2,
        noSac: true,
        sigils: [ 'gainGemAll' ],
        tribes: ['mox'],
    },
    muscleMage: {
        name: 'Muscle Mage',
        portrait: 'muscleMage',
        power: 1,
        health: 2,
        cost: { type: 'mox', needs: MoxType.Green },
        sigils: [ 'strafePush' ],
    },
    orangeMage: {
        name: 'Orange Mage',
        portrait: 'orangeMage',
        power: 0,
        health: 1,
        cost: { type: 'mox', needs: MoxType.Orange },
        sigils: [ 'buffGems' ],
    },
    practiceMage: {
        name: 'Practice Wizard',
        portrait: 'practiceMage',
        power: 0,
        health: 3,
        cost: { type: 'mox', needs: MoxType.Orange },
        sigils: [ 'stone' ],
    },
    magePupil: {
        name: 'Mage Pupil',
        portrait: 'magePupil',
        power: 1,
        health: 1,
        sigils: [ 'gemDependant' ],
    },
    rubyGolem: {
        name: 'Ruby Golem',
        portrait: 'rubyGolem',
        power: 1,
        health: 1,
        cost: { type: 'mox', needs: MoxType.Orange },
        noSac: true,
        sigils: [ 'dropRubyOnDeath' ],
    },
    stimMage: {
        name: 'Stim Mage',
        portrait: 'stimMage',
        power: 0,
        health: 2,
        cost: { type: 'mox', needs: MoxType.Green },
        // sigils: [ 'activatedStatsUpEnergy' ],
    },
    witheredCorpse: {
        name: 'Withered Corpse',
        portrait: 'witheredCorpse',
        power: 1,
        health: 1,
        sigils: [ 'brittle', 'boneless' ],
    },
    emptyVessel: {
        name: 'Empty Vessel',
        portrait: 'emptyVessel',
        power: 0,
        health: 3,
        cost: { type: 'energy', amount: 1 },
        noSac: true,
    },
};

// Check validity of references
for (const card of Object.values(prints)) {
    if (card.evolution && !Object.hasOwn(prints, card.evolution))
        throw new Error(`Card ${card.name} references invalid evolution ${card.evolution}`);
}
