import { Spritesheet } from '.';

export const SigilSprites: Spritesheet = {
    path: '/assets/gbc/sigils.png',
    size: [127, 163],
    tiled: {
        tileSize: [17, 17],
        borderWidth: { out: 1, in: 1 },
    },
    sprites: {
        bombSpewer: [0, 0],
        boneDigger: [1, 0],
        brittle: [2, 0],
        buffGems: [3, 0],
        conduitBuffAttack: [4, 0],
        conduitEnergy: [5, 0],
        conduitHealing: [0, 1],
        conduitSpawner: [1, 1],
        deathTouch: [2, 1],
        doubleDeath: [3, 1],
        drawCopy: [4, 1],
        unkillable: [5, 1],
        drawNewHand: [0, 2],
        drawRabbit: [1, 2],
        dropRubyOnDeath: [2, 2],
        evolve: [3, 2],
        detonator: [4, 2],
        detonatorFlipped: [5, 2],
        airborne: [0, 3],
        gainBattery: [1, 3],
        gainGemAll: [91, 55, 29, 17],
        gainGemBlue: [2, 3],
        gainGemGreen: [3, 3],
        gainGemOrange: [4, 3],
        gemDependant: [0, 4],
        gemsDraw: [1, 4],
        chaseOpposingPlay: [2, 4],
        frozen: [3, 4],
        looter: [4, 4],
        voidDamage: [5, 4],
        fourBones: [0, 5],
        mightyLeap: [1, 5],
        manyLives: [2, 5],
        sentry: [3, 5],
        sharp: [4, 5],
        skeletonStrafe: [5, 5],
        squirrelStrafe: [6, 1],
        steelTrap: [6, 2],
        strafe: [5, 6],
        strafePush: [6, 4],
        waterborne: [6, 5],
        waterborneTentacle: [0, 6],
        threeSacs: [1, 6],
        tristrike: [2, 6],
        bistrike: [6, 0],
        hoarder: [3, 6],
        chaseAttack: [4, 6],
        sniper: [6, 6],
        damBuilder: [1, 7],
        beesWithin: [2, 7],
        corpseEater: [3, 7],
        bellist: [4, 7],
        doubleAttack: [5, 7],
        leader: [6, 7],
        stinky: [0, 8],
        antSpawner: [1, 8],
        stone: [2, 8],
        boneless: [3, 8],

        vampiric: [0, 7],
    },
};
